### ISSUE TITLE
Spara databas i RAM för att spara flash?

### ISSUE THREAD

**Issue by avl** [avl/brygg#18]

**Comment by esnil** [comment]
Är det nödvändigt?
Med ett typ 16GB kort som vi nyttjar några procent av så är lär det behöva skrivas enormt mycket innan den är färdig. Även ett sdkort har väl logik för att sprida på slitaget?

**Comment by avl** [comment]
Fixat nu iaf. Med flera skrivningar i sekunden kunde ett dåligt sdkort bli utslitet om nån glömde maskinen på t.ex över en sommar eller likn.
