### ISSUE TITLE
Ange längd på resp temperatursteg

### ISSUE THREAD

**Issue by esnil** [avl/brygg#19]
Förslag för diskussion:

Istället för att ange tidpunkt för resp temperatur angivelse i guit, ange längd.

tex 20min med 60gr, 30 min med 65 osv.

När sedan styrningen körs så sätts faktiskt starttid av steget när denna temperatur är uppnådd, dvs bör-kurvan får en lutning mellan slutet av föregående steg och början på nästa som sätts av hur lång tid det faktiskt tog att värma/kyla till den temperaturen.

**Comment by avl** [comment]
Ponera att det tar 30 minuter att åstadkomma en viss temperturförändring. Ska man verkligen räkna bort den tiden helt och hållet? Om någon matar in 5 minuter på 25 grader, 5 minuter på 70, och sen 5 på 25, ska den då värma i 60 minuter för att komma upp i 70 grader, och sedan vila där i just 5 minuter, och sen masa sig ner till 25 och vila där ytterligare 5 innan den är klart?

Låter ganska rimligt, men för mig är det inte uppenbart att själva temperaturförändringstiden ska räknas bort helt från inmatade tider. Fast jag har inget jättemycket bättre förslag.

**Comment by esnil** [comment]
Jag har inget facit men jag får för mig att det är rätt små differanser, först från kallt till typ 60 sen kanske 65, 70 och slutligen 95. Syftet med en specifik temp är att vissa sockerarter mm kommer feam vid olika temp så det borde innebära att man inte kan starta klockan före 65 är uppnått.

Det går ju göra det konfigurerbart om vi är osäkra.

**Comment by avl** [comment]
Låter rimligt. Jag köper ditt resonemang.

**Comment by avl** [comment]
Har ändrat så att man anger längden på stegen istället för absolut minut-tal sen start.
Skapar ny ticket med nästa steg.
