### ISSUE TITLE
reglering med rattar och vred

### ISSUE THREAD

**Issue by esnil** [avl/brygg#20]
Som komplement till nuvvarande kurv-styrning:

Växla til "enkelt" läge, ta bort tidsangivelserna till höger och visa ett stort vred som man kan ställa in önskad tempteratur (eller ännu enklare bara en textbox där man får skriva).

Rita därefter ut grafen med är- och börvärden när man kör.

**Comment by avl** [comment]
Bra idé!

**Comment by avl** [comment]
Har implementerat "enkelt läge". Inte med nåt vred, men med en enkel textbox där man får skriva.

För att hålla reda på att det gjorts ett jobb så stänger jag den här. Om ett vred är viktigt så kan nån gärna öppna en ny issue för det :-).
