### ISSUE TITLE
Visa givare

### ISSUE THREAD

**Issue by esnil** [avl/brygg#22]
Visa i guit (kanske på en annan sida än huvudsidan) vilka ow-givare som finns tillgängliga på busen. Markera vilka som skall visas i grafen

**Comment by avl** [comment]
Det här är säkert möjligt, men jag tror inte att det är jättelätt. OWFS presenterar en sjujäkla massa saker på min dator. Om vi visar alla så blir det ganska plottrigt. Varför vill vi - vi vet väl vilken/vilka OW-givare vi köpt?

Eller är tanken att Alf ska kunna lägga till flera själv utan att behöva redigera config-filer motsv?

/Anders

**Comment by esnil** [comment]
Tänkte man kunde hakapå valfri givare sen för att tex övervaka jäsningen.

Man kan ju mata in serienumret manuellt men informationen finns redan så det kändes onödigt.

Jag kan kolla på owfs, det säkert konfigurerbart vilka givartyper den mappar upp. Det körs ju ingen onewire internt på datorn.

**Comment by avl** [comment]
Är du helt säker på att det inte körs onewire internt i datorn? Det finns en massa liknande teknik i datorn i alla fall. Typ I2c eller vad det heter? Men jag hoppas du har rätt. :-)

**Comment by avl** [comment]
Fixat. Klicka på länken "Mätare" för att komma till vyn "Administrera mätare"
