### ISSUE TITLE
Ska verkligen klockan stå stilla innan bör-värdet uppnåtts?

### ISSUE THREAD

**Issue by avl** [avl/brygg#29]
Att klockan gör det gör ju att temperaturhistoriken från bryggprocssen blir fel.

Jag tror, om vi ska ha kvar denna logik, att vi måste logga både "verklig" och "nominell" tid, så att man kan få ut en graf över verklig historisk temperaturutveckling, förutom den "nominella" temperaturutvecklingen i "brygg-tid".

På nåt sätt har vi liksom två tider: Nominell tid, och verklig tid.

**Comment by esnil** [comment]
Hmm, ja kanske. Men det som ska loggas är väl bara är-värde och det är ju inget annat än verklig tid. Börvärdena kan väl "flyta" och när lämpligt temperaturintervall är uppnått så börjar timern för det temperatursteget att snurra?

**Comment by avl** [comment]
Din föreslagna lösning med att börvärdena flyter borde kunna funka. Till dess vi implementerat det känner jag att vi stänger av "waiting"-funktionen. Så att tiden hela tiden tickar framåt.
