### ISSUE TITLE
Regleringen startar aldrig

### ISSUE THREAD

**Issue by esnil** [avl/brygg#31]
Startar upp allting och det får kontakt med givaren och tillsynes även med reläkort. I givar-administrationen så kan givaren avläsas.
När man sedan startar regleringen så händer inget alls, tiden tickar inte, givarvärdet uppdateras inte och det står att reläutgång ett är till (vilket den inte är på riktigt)

Kanske fixat av anders redan

**Comment by avl** [comment]
troligtvis fixat.
