### ISSUE TITLE
Dynamisk total tid

### ISSUE THREAD

**Issue by esnil** [avl/brygg#6]
Totala tiden för reglerkurvan borde sättas utifrån vad man ställt in. Och sedan måste den justeras utifrån den tid det tar att röra sig mellan tempereturnivåer.

**Comment by avl** [comment]
Det här får du gärna utveckla lite grand.

**Comment by esnil** [comment]
Fick för mig att nu är det lite låst till att reglera i en timme sen tar grafen slut. Det kanske tar tre timmar med uppvärmning och så.

**Comment by avl** [comment]
Ja, jag håller med. Vi borde komma till nån sorts beslut hur vi vill att allt detta ska funka. Vill man ha den här funktionen att kunna sätta upp en path som regleringen ska följa?

60 minuters maxtid är väldigt begränsat, jag håller med. Frågan är vad som ska hända om man kör längre? Scrolla? Scala om? Börja om från vänster? Paging?

**Comment by esnil** [comment]
Scrolla tycker jag är bättre än att skala, man blir lätt förvirrad om en axel plötsligt har bytt skala. Så scroll eller paging, det som är enklast och snabbast att implementera tycker jag.

**Comment by avl** [comment]
Nu har jag gjort så huvudfönstret scrollar. Man kan inte scrolla tillbaka, man ser helt enkelt bara de senaste 60 minuterna ungefär. Om man laddar ner loggen ser man hela processen. typ.

**Comment by avl** [comment]
Jag vet inte om jag egentligen löst problemet som rapporterades först i denna issue.

Nu går det i alla fall att reglera mer än 60 minuter.
